config/routes.rb
Train01::Application.routes.draw do
  resources :shipments

  resources :prod_subtypes

  resources :logs

  resources :contract_items

  resources :contracts
  match     '/contracts/:id/add_item',                to: 'contracts#add_item',            via: :get,  as: :add_contract_item
  match     '/contracts/:id/assign_item/:item_id',    to: 'contracts#assign_item',         via: :get,  as: :assign_contract_item_product
  match     '/contracts/:id/unassign_item',           to: 'contracts#unassign_item',       via: :post, as: :unassign_contract_item
  match     '/contracts/:id/adjust',                  to: 'contracts#adjust',              via: :post, as: :adjust_contract
  match     '/date_parts_required',                   to: 'contracts#parts_required',      via: :get,  as: :date_parts_required
  match     '/contracts_update',                      to: 'contracts#contracts_update',    via: :post, as: :contracts_update
  match     '/contracts/:id/copy',                    to: 'contracts#copy',                via: :post, as: :copy_contract
  match     '/contracts/:id/packing_list',            to: 'contracts#packing_list',        via: :get,  as: :packing_list
  match     '/contracts/:id/user_packing_list',       to: 'contracts#user_packing_list',   via: :get,  as: :user_packing_list
  match     '/contracts/:id/followup_packing_list',   to: 'contracts#followup_packing_list',  via: :get,  as: :followup_packing_list
  match     '/contracts/:id/inventory_packing_list',  to: 'contracts#inventory_packing_list', via: :get,  as: :inventory_packing_list
  match     '/contracts/:id/ship_assigned_items',     to: 'contracts#ship_assigned_items', via: :post, as: :ship_assigned_items
  match     '/contracts/:id/add_attachment',          to: 'contracts#add_attachment',      via: :post, as: :contract_add_attachment
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number',       via: :get,  as: :change_number
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number_apply', via: :post, as: :change_number_apply
  match     '/contracts/:id/add_ship_date',           to: 'contracts#add_ship_date',       via: :post, as: :add_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date',       via: :get,  as: :set_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date_apply', via: :post, as: :set_ship_date_apply
  match     '/contracts/:id/change_box',              to: 'contracts#change_box',          via: :get,  as: :change_contract_box
  match     '/contracts/:id/change_box',              to: 'contracts#change_box_apply',    via: :post, as: :change_contract_box_apply

  resources :product_statuses

  resources :products
  match     '/products/:id/change_box',     to: 'products#change_box',          via: :get,  as: :change_product_box
  match     '/products/:id/change_box',     to: 'products#change_box_apply',    via: :post, as: :change_product_box_apply
  match     '/products/:id/add_attachment', to: 'products#add_attachment',      via: :post, as: :product_add_attachment
  
  resources :prod_types
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype',          via: :get,  as: :add_prod_subtype
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype_apply',    via: :post
  match     '/prod_types/:id/remove_subtype', to: 'prod_types#remove_subtype_apply', via: :post, as: :remove_prod_subtype
  match     '/prod_types/:id/adjust',         to: 'prod_types#adjust',               via: :post, as: :adjust_prod_type
  match     '/prod_types/:id/add_attachment', to: 'prod_types#add_attachment',       via: :post, as: :prod_type_add_attachment

  resources :image_to_parts

  resources :attachments

  resources :item_statuses

  resources :part_types

  resources :image_to_samples

  resources :samples
  match     'samples/:id',     to: 'samples#add_image', via: :post
  match     'samples/:id/change_box', to: 'samples#change_box',          via: :get,  as: :change_sample_box
  match     'samples/:id/change_box', to: 'samples#change_box_apply',    via: :post, as: :change_sample_box_apply

  resources :warehouses

  resources :part_insts
  match     '/part_insts/create',    to: 'part_insts#create',     via: :post, as: :create_part_inst

  resources :boxes
  match     '/boxes/:id/content',    to: 'boxes#content',         via: :get, as: :inspect_content
  match     '/boxes/:id/content',    to: 'boxes#merge_identical', via: :post, as: :merge_identical
  match     '/boxes/:id/add/:part',  to: 'boxes#add',             via: :get, as: :add_part_insts
  match     '/boxes/:id/add/:part',  to: 'boxes#add_apply',       via: :post
  match     '/boxes/:id/take/:part', to: 'boxes#take',            via: :get, as: :take_part_insts
  match     '/boxes/:id/take/:part', to: 'boxes#take_apply',      via: :post
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part',  via: :get, as: :add_new_part_to_box
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part_apply', via: :post

  resources :subparts

  resources :parts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts',          via: :get,  as: :add_subparts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts_apply',    via: :post
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts',       via: :get,  as: :remove_subparts
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts_apply', via: :post
  match      'parts/:id/estimate',         to: 'parts#estimate',              via: :get,  as: :estimate
  match      'parts/:id/estimate',         to: 'parts#estimate_take',         via: :post
  match      'parts/:id/show_production',  to: 'parts#show_production',       via: :get,  as: :show_production
  match      'parts/:id/show_production_apply', to: 'parts#show_production_apply', via: :post
  match      'parts/:id/add_image',        to: 'parts#add_image',             via: :post, as: :part_add_image
  match      'parts/:id/add_attachment',   to: 'parts#add_attachment',        via: :post, as: :part_add_attachment
  match      'parts/:id/copy',             to: 'parts#copy',                  via: :post, as: :copy_part
  match      'parts/:id/bom',              to: 'parts#bom',                   via: :get,  as: :part_bom
  
  resources :items
  match     '/items/:id/convert_form',     to: 'items#convert_form', via: :get,  as: :convert_form
  match     '/items/:id/convert_form',     to: 'items#convert',      via: :post
  match     '/my_items',                   to: 'items#my',           via: :get,  as: :my_items
  match     '/items/:id/copy',             to: 'items#copy',         via: :get,  as: :copy_item
  match     '/items/:id/copy',             to: 'items#copy_submit',  via: :post
  
  resources :orders

  
  get "static_pages/index"
  match '/static_pages/submit',            to: 'static_pages#submit',            via: :post
  match '/static_pages/submitImage',       to: 'static_pages#submitImage',       via: :post
  match '/static_pages/new_user_form',     to: 'static_pages#new_user_form',     via: :get
  match '/static_pages/user_sign_in_form', to: 'static_pages#user_sign_in_form', via: :get
  match '/static_pages/user_sign_in',      to: 'static_pages#user_sign_in',      via: :post
  match '/static_pages/user_sign_out',     to: 'static_pages#user_sign_out',     via: :post
  match '/static_pages/user_register',     to: 'static_pages#user_register',     via: :post, as: :user_register

  root 'static_pages#index'

  resources :users
  match "/users",            to: "users#all",     via: :get,        as: :users_all
  get   "/users/:id"         =>  "users#show",    as:  :users_show
  get   "/users/:id/edit"    =>  "users#edit",    as:  :users_edit
  match "/users/:id/update", to: "users#update",  via: :post

  resources :orders
  match     "/orders/update", to: "orders#update",  via: :post
  get       "/my_orders"      => "orders#my_orders", as: :my_orders

end

app/models/sample.rb
# == Schema Information
#
# Table name: samples
#
#  id          :integer          not null, primary key
#  from        :text
#  desc        :text
#  received    :datetime
#  due         :datetime
#  user_placed :integer
#  user_resp   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  location    :text
#  status      :integer
#  warn_days   :integer
#  box_id      :integer
#

class Sample < ActiveRecord::Base
  attr_accessible :from
  attr_accessible :desc
  attr_accessible :received
  attr_accessible :due
  attr_accessible :user_placed
  attr_accessible :user_resp
  attr_accessible :location
  attr_accessible :status
  attr_accessible :warn_days
  attr_accessible :box_id


  def add_image( image, desc )
    img = Image.new
    img.avatar = image
    img.desc   = desc
    if not img.save then
      return nil
    end

    img2sam = ImageToSample.new
    img2sam.image_id  = img.id
    img2sam.sample_id = self.id
    if ( not img2sam.save ) then
      return nil
    end

    return img
  end


  def images()
    img2sams = ImageToSample.where( sample_id: self.id )
    images = []
    img2sams.each do|img2sam|
      if ( Image.exists?( img2sam.image_id ) ) then
        images.append( Image.find( img2sam.image_id ) )
      end
    end
    return images
  end

  def user_placed_name()
    if ( User.exists?( self.user_placed ) )
      user = User.find( self.user_placed )
      name = user.name + ' ' + user.surname
      return name
    end
    return 'unspecified'
  end

  def user_resp_name()
    if ( User.exists?( self.user_resp ) )
      user = User.find( self.user_resp )
      name = user.name + ' ' + user.surname
      return name
    end
    return 'unspecified'
  end

  @@STATUS_PENDING    = 0
  @@STATUS_IN_MEASURE = 1
  @@STATUS_COMPLETED  = 2
  
  @@DEFAULT_WARN_DAYS = 7

  def Sample.status_list()
    res = {}
    res[ @@STATUS_PENDING ]    = "pending"
    res[ @@STATUS_IN_MEASURE ] = "in measure"
    res[ @@STATUS_COMPLETED ]  = "completed"
    return res
  end

  def status_stri()
    st = self.status || @@STATUS_PENDING
    return Sample.status_list()[ st ]
  end

  # Status completed?
  def completed?()
    return (self.status == @@STATUS_COMPLETED)
  end

  def still_valid?()
    if completed?() then
      return true
    end
    warn_days = (self.warn_days || @@DEFAULT_WARN_DAYS).to_f
    due_time  = self.due
    now_time  = Time.now
    left_days = (due_time - now_time).to_f / (24*60*60).to_f
    return (left_days > warn_days)
  end

  def box()
    res = Box.exists?( self.box_id )
    if ( not res )
      return nil
    end
    res = Box.find( self.box_id )
    return res
  end

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  include UsersHelper
  include ItemsHelper
  include LogsHelper

  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @user = current_user

    if ( params[ :search ] ) then
        @paginate = false
        @samples = search( Sample, params[ :search ], [ 'from', 'desc', 'location' ] )
    else
        @paginate = true
        @samples = Sample.paginate( page: params[:page], per_page: 10, order: "id DESC" )
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @user = current_user
  end

  # GET /samples/new
  def new
    @user = current_user
    @sample = Sample.new
    @users = users

    @warn_days = 7

    @status = []
    Sample.status_list().each do |k, v|
      @status.append( [v, k] )
    end
  end

  # GET /samples/1/edit
  def edit
    @user = current_user
    @users = users

    @warn_days = 7

    @status = []
    Sample.status_list().each do |k, v|
      @status.append( [v, k] )
    end

  end

  # POST /samples
  # POST /samples.json
  def create
    @user = current_user
    @sample = Sample.new(sample_params)
    @sample.user_placed = @user.id

    respond_to do |format|
      if @sample.save
        log( "New sample is added: " + @sample.desc, @user )

        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sample }
      else
        format.html { render action: 'new' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @sample.update( sample_params )
        log( "New sample is updated: " + @sample.desc, @user )

        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  #def destroy
  #  @user = current_user
    #@sample.destroy
  #  respond_to do |format|
  #    format.html { redirect_to samples_url }
  #    format.json { head :no_content }
  #  end
  #end

  def add_image
    @user = current_user
    sample = Sample.find( params[ :id ] )
    image  = params[ :image ]
    desc   = params[ :desc ] || ''
    sample.add_image( image, desc )
    redirect_to sample, notice: 'Image is added to this sample!'
  end

  def change_box
    @user  = current_user
    @sample = Sample.find( params[ :id ] )
    if ( params[:search] && (params[:search].size > 0) )
      @boxes = search( Box, params[:search], [ "box_id", "desc" ] )
      @paginate = false
    else
      @boxes = Box.paginate( page: params[ :page ], per_page: 30 )
      @paginate = true
    end
  end

  def change_box_apply
    @user  = current_user
    @sample = Sample.find( params[ :id ] )
    @sample.box_id = params[ :box_id ]
    if ( @sample.save )
      redirect_to @sample, notice: 'The sample was moved to a different place.'
    else
      redirect_to change_sample_box_path( @product.id ), notice: 'Failed to move the sample to a different place.'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit( :from, :desc, :received, :due, :user_placed, 
                                      :user_resp, :status, :warn_days, :location, :box_id )
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Received from' %><br>
    <%= f.text_area :from, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Sample description' %><br>
    <%= f.text_area :desc, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Where this sample is located' %><br>
    <%= f.text_area :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Received date' %><br>
    <%= f.datetime_select :received, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Due date' %><br>
    <%= f.datetime_select :due, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Person responsible' %><br>
    <%= f.select :user_resp, @users, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Current status' %><br>
    <%= f.select :status, @status, selected: (@sample.status || 0), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'Warn application scientist in [x] days' %><br>
    <%= f.number_field :warn_days, value: @warn_days || 7, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Add/update sample', class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/samples/change_box.html.erb
<h2>Select Sample location</h2>

<% if @sample.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @sample.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<p>
  <strong>From:</strong>
  <%= @sample.from %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @sample.desc %>
</p>

<p>
  <strong>Sample location:</strong>
  <%= @sample.location %>
</p>

<p>
  <strong>Received:</strong>
  <%= @sample.received %>
</p>

<% if not @sample.still_valid? %>
  <p class="critical_cnt">
<% else %>
  <% if @sample.completed?%>
    <p class="completed">
  <%else%>
    <p>
  <% end %>
<% end %>
  <strong>Due:</strong>
  <%= @sample.due %>
</p>

<p>
  <strong>User placed:</strong>
  <%= @sample.user_placed_name %>
</p>

<p>
  <strong>User resp:</strong>
  <%= @sample.user_resp_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sample.status_stri %>
</p>

<%if @paginate%>
  <%=will_paginate( @boxes, renderer: BootstrapPagination::Rails )%>
<%end%>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Warehouse</th>
      <th>Box</th>
      <th>Desc</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>
        <%= form_tag( change_sample_box_apply_path( @sample.id ), method: 'post' ) do %>
          <%=submit_tag 'Not in a box, somewhere in the office', class: 'btn btn-warning'%>
          <%=hidden_field_tag( :box_id, -1 )%>
        <%end%>
      </td>
  	</tr>
    <% @boxes.each do |box| %>
      <tr>
        <td>
            <%if box.warehouse then %>
              <%=box.warehouse.w_id%>
            <%else%>
              Unspecified
            <%end%>
        </td>
        <td><%= box.box_id %></td>
        <td><%= box.desc %></td>
        <td><%= link_to 'Show', box %></td>
        <td>
          <%= form_tag( change_sample_box_apply_path( @sample.id ), method: 'post' ) do %>
            <%=submit_tag 'Put it here', class: 'btn btn-warning'%>
            <%=hidden_field_tag( :box_id, box.id )%>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Show sample', @sample %> |
<%= link_to 'All samples', samples_path() %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<%= link_to 'Add new sample', new_sample_path, class: "btn btn-warning" %>
<br>
<br>

<% if (@paginate == nil) || @paginate %>
  <%= will_paginate @samples, renderer: BootstrapPagination::Rails %>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Received from</th>
      <th>Location</th>
      <th>Due date</th>
      <th>User responsible</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <%if not sample.still_valid? then%>
        <%cl="danger"%>
      <%else%>
        <%if sample.completed?%>
          <%cl="success"%>
        <%else%>
          <%cl=""%>
        <%end%>
      <%end%>
      <tr>
        <td class="<%=cl%>"><%= sample.from %></td>
        <td class="<%=cl%>"><%= sample.location %></td>
        <td class="<%=cl%>"><%= sample.due %></td>
        <td class="<%=cl%>"><%= sample.user_resp_name %></td>
        <td class="<%=cl%>"><%= sample.status_stri %></td>
        <td><%= link_to 'Show', sample, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample), class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new sample', new_sample_path, class: "btn btn-warning" %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @sample.from %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @sample.desc %>
</p>

<p>
  <strong>Sample location:</strong>
  <%= @sample.location %>
</p>

<p>
  <strong>Received:</strong>
  <%= @sample.received %>
</p>

<% if not @sample.still_valid? %>
  <p class="critical_cnt">
<% else %>
  <% if @sample.completed?%>
    <p class="completed">
  <%else%>
    <p>
  <% end %>
<% end %>
  <strong>Due:</strong>
  <%= @sample.due %>
</p>

<p>
  <strong>User placed:</strong>
  <%= @sample.user_placed_name %>
</p>

<p>
  <strong>User resp:</strong>
  <%= @sample.user_resp_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sample.status_stri %>
</p>

<p>
  <%@box = @sample.box()%>
  <%if @box%>
    <strong>This sample is in this <%=link_to( 'box', box_path( @box.id ) )%>:</strong>
    <%=render( 'boxes/show' )%>
  <%else%>
    This sample is not in a box, try find it somewhere in the office.
  <%end%>
</p>


<table class="table table-bordered table-hover">
  <%@sample.images.each do |image|%>
    <tr>
      <td>
        <a href="<%=image.avatar.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
            <%=image_tag( image.avatar.url(:thumb) )%>
        </a>
      </td>
      <td>
        <%= image.desc %>
      </td>
    </tr>
  <%end%>
</table>

<%= form_tag( sample_path( @sample.id ), multipart: true ) do %>
  <%= file_field_tag "image" %>
  <%= text_area_tag :desc %>
  <%= submit_tag 'Append image', class: 'button large' %>
<%end%>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'All Samples', samples_path %> | 
<%= link_to 'Change location', change_sample_box_path( @sample.id )%>