config/routes.rb
Train01::Application.routes.draw do
  resources :shipments

  resources :prod_subtypes

  resources :logs

  resources :contract_items

  resources :contracts
  match     '/contracts/:id/add_item',                to: 'contracts#add_item',            via: :get,  as: :add_contract_item
  match     '/contracts/:id/assign_item/:item_id',    to: 'contracts#assign_item',         via: :get,  as: :assign_contract_item_product
  match     '/contracts/:id/unassign_item',           to: 'contracts#unassign_item',       via: :post, as: :unassign_contract_item
  match     '/contracts/:id/adjust',                  to: 'contracts#adjust',              via: :post, as: :adjust_contract
  match     '/date_parts_required',                   to: 'contracts#parts_required',      via: :get,  as: :date_parts_required
  match     '/contracts_update',                      to: 'contracts#contracts_update',    via: :post, as: :contracts_update
  match     '/contracts/:id/copy',                    to: 'contracts#copy',                via: :post, as: :copy_contract
  match     '/contracts/:id/packing_list',            to: 'contracts#packing_list',        via: :get,  as: :packing_list
  match     '/contracts/:id/user_packing_list',       to: 'contracts#user_packing_list',   via: :get,  as: :user_packing_list
  match     '/contracts/:id/followup_packing_list',   to: 'contracts#followup_packing_list',  via: :get,  as: :followup_packing_list
  match     '/contracts/:id/inventory_packing_list',  to: 'contracts#inventory_packing_list', via: :get,  as: :inventory_packing_list
  match     '/contracts/:id/ship_assigned_items',     to: 'contracts#ship_assigned_items', via: :post, as: :ship_assigned_items
  match     '/contracts/:id/add_attachment',          to: 'contracts#add_attachment',      via: :post, as: :contract_add_attachment
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number',       via: :get,  as: :change_number
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number_apply', via: :post, as: :change_number_apply
  match     '/contracts/:id/add_ship_date',           to: 'contracts#add_ship_date',       via: :post, as: :add_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date',       via: :get,  as: :set_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date_apply', via: :post, as: :set_ship_date_apply
  match     '/contracts/:id/change_box',              to: 'contracts#change_box',          via: :get,  as: :change_contract_box
  match     '/contracts/:id/change_box',              to: 'contracts#change_box_apply',    via: :post, as: :change_contract_box_apply

  resources :product_statuses

  resources :products
  match     '/products/:id/change_box',     to: 'products#change_box',          via: :get,  as: :change_product_box
  match     '/products/:id/change_box',     to: 'products#change_box_apply',    via: :post, as: :change_product_box_apply
  match     '/products/:id/add_attachment', to: 'products#add_attachment',      via: :post, as: :product_add_attachment
  
  resources :prod_types
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype',          via: :get,  as: :add_prod_subtype
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype_apply',    via: :post
  match     '/prod_types/:id/remove_subtype', to: 'prod_types#remove_subtype_apply', via: :post, as: :remove_prod_subtype
  match     '/prod_types/:id/adjust',         to: 'prod_types#adjust',               via: :post, as: :adjust_prod_type
  match     '/prod_types/:id/add_attachment', to: 'prod_types#add_attachment',       via: :post, as: :prod_type_add_attachment

  resources :image_to_parts

  resources :attachments

  resources :item_statuses

  resources :part_types

  resources :image_to_samples

  resources :samples
  match     'samples/:id',     to: 'samples#add_image', via: :post
  match     'samples/:id/change_box', to: 'samples#change_box',          via: :get,  as: :change_sample_box
  match     'samples/:id/change_box', to: 'samples#change_box_apply',    via: :post, as: :change_sample_box_apply

  resources :warehouses

  resources :part_insts
  match     '/part_insts/create',    to: 'part_insts#create',     via: :post, as: :create_part_inst

  resources :boxes
  match     '/boxes/:id/content',    to: 'boxes#content',         via: :get, as: :inspect_content
  match     '/boxes/:id/content',    to: 'boxes#merge_identical', via: :post, as: :merge_identical
  match     '/boxes/:id/add/:part',  to: 'boxes#add',             via: :get, as: :add_part_insts
  match     '/boxes/:id/add/:part',  to: 'boxes#add_apply',       via: :post
  match     '/boxes/:id/take/:part', to: 'boxes#take',            via: :get, as: :take_part_insts
  match     '/boxes/:id/take/:part', to: 'boxes#take_apply',      via: :post
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part',  via: :get, as: :add_new_part_to_box
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part_apply', via: :post

  resources :subparts

  resources :parts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts',          via: :get,  as: :add_subparts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts_apply',    via: :post
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts',       via: :get,  as: :remove_subparts
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts_apply', via: :post
  match      'parts/:id/estimate',         to: 'parts#estimate',              via: :get,  as: :estimate
  match      'parts/:id/estimate',         to: 'parts#estimate_take',         via: :post
  match      'parts/:id/show_production',  to: 'parts#show_production',       via: :get,  as: :show_production
  match      'parts/:id/show_production_apply', to: 'parts#show_production_apply', via: :post
  match      'parts/:id/add_image',        to: 'parts#add_image',             via: :post, as: :part_add_image
  match      'parts/:id/add_attachment',   to: 'parts#add_attachment',        via: :post, as: :part_add_attachment
  match      'parts/:id/copy',             to: 'parts#copy',                  via: :post, as: :copy_part
  match      'parts/:id/bom',              to: 'parts#bom',                   via: :get,  as: :part_bom
  
  resources :items
  match     '/items/:id/convert_form',     to: 'items#convert_form', via: :get,  as: :convert_form
  match     '/items/:id/convert_form',     to: 'items#convert',      via: :post
  match     '/my_items',                   to: 'items#my',           via: :get,  as: :my_items
  match     '/items/:id/copy',             to: 'items#copy',         via: :get,  as: :copy_item
  match     '/items/:id/copy',             to: 'items#copy_submit',  via: :post
  
  resources :orders

  
  get "static_pages/index"
  match '/static_pages/submit',            to: 'static_pages#submit',            via: :post
  match '/static_pages/submitImage',       to: 'static_pages#submitImage',       via: :post
  match '/static_pages/new_user_form',     to: 'static_pages#new_user_form',     via: :get
  match '/static_pages/user_sign_in_form', to: 'static_pages#user_sign_in_form', via: :get
  match '/static_pages/user_sign_in',      to: 'static_pages#user_sign_in',      via: :post
  match '/static_pages/user_sign_out',     to: 'static_pages#user_sign_out',     via: :post
  match '/static_pages/user_register',     to: 'static_pages#user_register',     via: :post, as: :user_register

  root 'static_pages#index'

  resources :users
  match "/users",            to: "users#all",     via: :get,        as: :users_all
  get   "/users/:id"         =>  "users#show",    as:  :users_show
  get   "/users/:id/edit"    =>  "users#edit",    as:  :users_edit
  match "/users/:id/update", to: "users#update",  via: :post

  resources :orders
  match     "/orders/update", to: "orders#update",  via: :post
  get       "/my_orders"      => "orders#my_orders", as: :my_orders

end

app/controllers/prod_types_controller.rb
class ProdTypesController < ApplicationController
  include UsersHelper
  include PartsHelper
  include LogsHelper

  before_action :set_prod_type, only: [:show, :edit, :update]

  # GET /prod_types
  # GET /prod_types.json
  def index
    if ( params[ :search ] && (params[ :search ].size > 0) ) then
      @paginate   = false
      @prod_types = search( ProdType, params[ :search ], [ 'own_id', 'desc' ] )
    else
      @paginate   = true
      @prod_types = ProdType.paginate( page: params[:page], per_page: 10, order: "id DESC" )
    end
    @user  = current_user
    #@prod_types = ProdType.all
  end

  # GET /prod_types/1
  # GET /prod_types/1.json
  def show
    @user           = current_user
    @prod_type      = ProdType.find( params[ :id ] )
    search          = params[ :search ]
    @products, @paginate = @prod_type.products( params.to_hash, search, params[ :page ] )
    
    @subproducts = @prod_type.subproducts
  end

  # GET /prod_types/new
  def new
    @prod_type = ProdType.new
    if ( params[ :search ] && (params[ :search ].size > 0) ) then
      @paginate = false
      @parts    = search( Part, params[ :search ], [ 'own_id', 'third_id', 'desc' ] )
    else
      @paginate = true
      @parts    = Part.paginate( page: params[:page], per_page: 10 )
    end

    @user  = current_user
  end

  # GET /prod_types/1/edit
  def edit
    @user  = current_user
    @prod_type = ProdType.find( params[ :id ] )
    if ( params[ :search ] && (params[ :search ].size > 0) ) then
      @paginate = false
      @parts    = search( Part, params[ :search ], [ 'own_id', 'third_id', 'desc' ] )
    else
      @paginate = true
      @parts    = Part.paginate( page: params[:page], per_page: 10 )
    end

    @subproducts = @prod_type.subproducts
  end

  # POST /prod_types
  # POST /prod_types.json
  def create
    @user  = current_user
    #debugger
    @prod_type         = ProdType.new(prod_type_params)
    @prod_type.user_id = @user.id
    @prod_type.part_id = params[ :part_id ] || -1
    @prod_type.image   = params[ :prod_type ][ :image ]
    @prod_type.packing_details = params[ :prod_type ][ :packing_details ]

    respond_to do |format|
      if @prod_type.save
        log( "New product type is created: " + @prod_type.own_id, @user )

        format.html { redirect_to @prod_type, notice: 'Prod type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @prod_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @prod_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prod_types/1
  # PATCH/PUT /prod_types/1.json
  def update
    @user                      =   current_user
    @prod_type.part_id         = params[ :part_id ]  || @prod_type.part_id || -1
    @prod_type.image           = params[ :prod_type ][ :image ] || @prod_type.image
    @prod_type.packing_details = params[ :prod_type ][ :packing_details ] || @prod_type.packing_details
    respond_to do |format|
      if @prod_type.update(prod_type_params)
        log( "Product type is adjusted: " + @prod_type.own_id, @user )

        format.html { redirect_to @prod_type, notice: 'Prod type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prod_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prod_types/1
  # DELETE /prod_types/1.json
  #def destroy
  #  @user  = current_user
  #  @prod_type.destroy
  #  respond_to do |format|
  #    format.html { redirect_to prod_types_url }
  #    format.json { head :no_content }
  #  end
  #end

  def add_subtype
    @user      = current_user
    @prod_type = ProdType.find( params[ :id ] )
    
    stri     = params[ :search ]
    if ( stri && ( stri.size > 0 ) )
      @prod_types = search( ProdType, stri, ['own_id', 'desc'] )
    else
      @prod_types = ProdType.all.page( params[:page] )
    end
  end

  def add_subtype_apply
    @user      = current_user
    @prod_type = ProdType.find( params[ :id ] )

    pst = ProdSubtype.new
    pst.belongs_id  = @prod_type.id
    pst.contains_id = params[ :contains_id ]
    if pst.save
      redirect_to( edit_prod_type_path( @prod_type.id ), notice: 'Successfully added product subtype.' )
    else
      redirect_to( edit_prod_type_path( @prod_type.id ), notice: 'Failed to add product subtype.' )
    end
  end

  def remove_subtype_apply
    @user      = current_user
    @prod_type = ProdType.find( params[ :id ] )
    pst = ProdSubtype.find( params[ :subtype_id ] )

    pst.delete
    pst.save
    redirect_to( edit_prod_type_path( @prod_type.id ), notice: 'Removed product type internal part.' )
  end

  def adjust
    @user      = current_user
    @prod_type = ProdType.find( params[ :id ] )
    part_id    = params[ :part_id ] || -1
    @prod_type.part_id = part_id
    @prod_type.save

    redirect_to( edit_prod_type_path( @prod_type.id ), notice: 'Removed product type internal part.' )
  end

  def add_attachment
    show()
    file = params[ :file ]
    desc = params[ :desc ]
    if ( @prod_type.add_attachment( file, desc ) )
      redirect_to( prod_type_path( @prod_type.id ), notice: "File has been added!" )
    else
      redirect_to( prod_type_path( @prod_type.id ), notice: "ERROR: Failed to add file!" )
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prod_type
      @prod_type = ProdType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prod_type_params
      params.require( :prod_type ).permit( :part_id, :own_id, :desc, :image, 
                                           :client_visible, :packing_details, :pack_to )
    end
end

app/helpers/prod_types_helper.rb
module ProdTypesHelper
end

app/views/prod_types/_form.html.erb
<%= form_for(@prod_type, :html => { :multipart => true }) do |f| %>
  <% if @prod_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prod_type.errors.count, "error") %> prohibited this prod_type from being saved:</h2>

      <ul>
      <% @prod_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit "Create/update product type", class: 'btn btn-warning' %>
  </div>
  <div class="form-group">
    <%= f.label 'Product image (if left blank part image is taken instead)'%>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Part catalog Id" %><br>
    <%= f.text_field :own_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Description" %><br>
    <%= f.text_area :desc, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Invisible in client packing list" %><br>
    <%= f.check_box :client_visible, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Packing notes for client packing list" %><br>
    <%= f.text_area :packing_details, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Recommended to pack to the following box:" %><br>
    <%= f.text_field :pack_to, class: "form-control" %>
  </div>
<% end %>
<br>

<%if ( @prod_type && @prod_type.id )%>
  <%if ( not (@prod_type.subproducts.size > 0) )%>
    <%=form_tag( adjust_prod_type_path( @prod_type.id ), :method => "post" ) do%>
      <%= submit_tag "No base part, this is pure assembly" %>
      <%= hidden_field_tag :part_id, -1 %>
    <%end%>
    <br>

    <%if @paginate then%>
      <%=will_paginate @parts, param_name: :page, renderer: BootstrapPagination::Rails %>
    <%end%>
    <table class="table table-bordered table-hover">
      <% @parts.each do |part| %>
        <tr>
          <td>
            <% @part = part %>
            <%= render 'parts/show' %>
          </td>

          <td>
            <%=form_tag( adjust_prod_type_path( @prod_type.id ), :method => "post" ) do%>
              <%= submit_tag "Base on this part" %>
              <%= hidden_field_tag :part_id, part.id %>
            <%end%>
          </td>
        </tr>
      <%end%>
    </table>
  <%else%>
    This product type contrains subproducts and can't be based on a part. To base this product type on a particular part type remove all subproducts first.
  <%end%>
<%else%>
  Assigning part type to this product will be available after creation.
<%end%>
<br>

app/views/prod_types/_show.html.erb
<%assembly = (@prod_type.subproducts.size() > 0)%>
<%if assembly%>
  This is an assembly product type consisting of one or several subproducts.
<%else%>
  <%= link_to 'Add new product to the list', new_product_path( @prod_type, prod_type_id: @prod_type.id ), class: "btn btn-warning" %>
<%end%>
<br>
<br>

<p>
    <a href="<%=@prod_type.image_ex.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
        <%=image_tag( @prod_type.image_ex.url(:thumb) )%>
    </a>
</p>

<p>
  <strong>Part number:</strong>
  <br>
  <%= @prod_type.own_id %>
</p>

<p>
  <strong>Quantity in stock:</strong>
  <br>
  <%= @prod_type.cnt_in_stock %>
</p>

<p>
  <strong>Quantity available:</strong>
  <br>
  <%= @prod_type.cnt_ready_for_sale %>
</p>

<p>
  <strong>Quantity unassigned:</strong>
  <br>
  <%= @prod_type.cnt_unassigned %>
</p>

<p>
  <strong>Quantity total:</strong>
  <br>
  <%= @prod_type.cnt_total %>
</p>

<p>
  <strong>Product description:</strong>
  <br>
  <%= @prod_type.desc %>
</p>

<p>
  <strong>Product is invisible in client's packing list:</strong>
  <br>
  <%= @prod_type.client_visible ? "invisible" : "visible" %>
</p>

<p>
  <strong>Recommended to pack to the following box:</strong>
  <%= @prod_type.pack_to_stri %>
</p>

<p>
  <strong>Client's packing list details:</strong>
  <br>
  <%= @prod_type.packing_details.to_s %>
</p>


<%if @prod_type.part%>
  <p>
    <strong>Product id based on this part:</strong>
    <br>
    <a href="<%=@prod_type.part.image.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
      <%=image_tag( @prod_type.part.image.url(:thumb) )%>
    </a>
    <%= link_to( @prod_type.part.own_id, part_path( @prod_type.part.id ) ) %>
  </p>
<%else%>
  <p>
    <%if assembly%>
      This product type is an assembly.
    <%else%>
      <h3 = class="critical_cnt">
        Warning: this product type is neither based on any part nor is an assembly. Due to this it has no information about assembling, pricing or parts included. It will not be taken into account when calculating contract statuses.
      </h3>
    <%end%>
  </p> 
<%end%>

<p>
  <strong>User introduced this product:</strong>
  <br>
  <%= @prod_type.user_name %>
</p>


<%if @subproducts && (@subproducts.size > 0)%>
  <strong>Subtypes list</strong>
  <table class="table table-bordered table-hover">
    <%@subproducts.each do |pair|%>
      <%spt = pair[:type]%>
      <%pt  = pair[:subtype]%>
      <tr>
        <td>
          <a href="<%=spt.image_ex.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
              <%=image_tag( spt.image_ex.url(:thumb) )%>
          </a>
        </td>
        <td>
          <%=link_to( spt.own_id, prod_type_path( spt.id ) )%>
        </td>
        <td>
          <%= spt.cnt %>
        </td>
        <td>
          <%= spt.desc %>
        </td>
      </tr>
    <%end%>
  </table>
<%end%>
<br>

app/views/prod_types/add_subtype.html.erb
<p id="notice"><%= notice %></p>

<strong>Add product subtype.</strong>

<p>
  <strong>Part number:</strong>
  <%= @prod_type.own_id %>
</p>

  <p>
    Choose part type form the list.
  </p>

  <div class="prod_subtypes_list">
    <%if @paginate then%>
      <%=will_paginate @prod_types, renderer: BootstrapPagination::Rails %>
    <%end%>
    <table class="table table-bordered table-hover">
      <% @prod_types.each do |pt| %>
        <%if pt.id != @prod_type.id then%>
          <tr>
            <td>
              <%= form_tag( add_prod_subtype_path( @prod_type.id ), method: :post ) do %>
                <%= submit_tag "Add this" %>
                <%= hidden_field_tag :contains_id, pt.id %>
              <%end%>
            </td>
            
            <td>
              <a href="<%=pt.image_ex.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
                <%=image_tag( pt.image_ex.url(:thumb) )%>
              </a>
            </td>
            <td>
              <%=link_to( pt.own_id, prod_type_path( pt.id ) ) %></td>
            </td>
            <td>
              <%=pt.desc%>
            </td>
          </tr>
        <%end%>
      <%end%>
    </table>        
  </div>


<%= link_to 'Back', edit_prod_type_path( @prod_type.id ) %>

app/views/prod_types/edit.html.erb
<h1>Editing this product type</h1>
<%= link_to 'View product type', @prod_type, class: "btn btn-success" %>
<br>

<%if not @prod_type.part%>
<%=link_to( "Add subproduct to this assembly (or make assembly from this single product type)", add_prod_subtype_path( @prod_type.id ) )%>
<br>
<%else%>
  This product type can't contain subproducts, because it is based on a part. To make product assembly remove part it is based on.
<%end%>

<%if @subproducts && (@subproducts.size > 0)%>
  <strong>Subtypes list</strong>
  <table class="table table-bordered table-hover">
    <%@subproducts.each do |pair|%>
      <%spt = pair[:type]%>
      <%pt  = pair[:subtype]%>
      <tr>
        <td>
          <a href="<%=spt.image_ex.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
              <%=image_tag( spt.image_ex.url(:thumb) )%>
          </a>
        </td>
        <td>
          <%=link_to( spt.own_id, prod_type_path( spt.id ) )%>
        </td>
        <td>
          <%= spt.cnt %>
        </td>
        <td>
          <%= spt.desc %>
        </td>
        <td>
          <%if pt.belongs_id == @prod_type.id%>
            <%=form_tag( remove_prod_subtype_path( @prod_type.id ), :method => 'post' ) do%>
              <%= hidden_field_tag :subtype_id, pt.id %>
              <%= submit_tag "Remove this postion"%>
            <%end%>
          <%end%>
        </td>
      </tr>
    <%end%>
  </table>
<%end%>
<br>

<%= render 'form' %>
<br>

<%= link_to 'View product type', @prod_type, class: "btn btn-success" %>

app/views/prod_types/index.html.erb
<h1>Product types</h1>

<%= link_to 'Add new product type', new_prod_type_path, class: 'btn btn-warning' %>
<br>
<br>

<%if @paginate%>
  <%=will_paginate( @prod_types, renderer: BootstrapPagination::Rails  )%>
<%end%>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Image</th>
      <th>Part number</th>
      <th>Description</th>
      <th>Cnt in stock</th>
      <th>Cnt in production</th>
      <th>Ordered cnt</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @prod_types.each do |prod_type| %>
      <%valid = prod_type.valid_product?%>
      <%if valid%>
        <%cl = ""%>
      <%else%>
        <%cl = "critical_cnt"%>
      <%end%>
      <tr>
        <td>
          <a href="<%=prod_type.image_ex.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
            <%=image_tag( prod_type.image_ex.url(:thumb) )%>
          </a>
        </td>
        <td class="<%=cl%>"><%= prod_type.own_id %></td>
        <td class="<%=cl%>"><%= prod_type.desc %></td>
        <td class="<%=cl%>"><%= prod_type.cnt %></td>
        <td class="<%=cl%>"><%= prod_type.cnt_for_import %></td>
        <td class="<%=cl%>">
          <%part = prod_type.part%>
          <%if part%>
            <%ordered_cnt, items = part.ordered_cnt%>
            <%if not part.has_subparts?%>
              <%=ordered_cnt.to_s%>
            <%else%>
              This is an assembly
            <%end%>
          <%end%>
        </td>
        <td><%= link_to 'Show', prod_type, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_prod_type_path(prod_type), class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new product type', new_prod_type_path, class: 'btn btn-warning' %>

app/views/prod_types/new.html.erb
<h1>New prod_type</h1>

<%= render 'form' %>

<%= link_to 'Back', prod_types_path %>

app/views/prod_types/show.html.erb
<p id="notice"><%= notice %></p>

<%part = @prod_type.part%>
<%if part%>
  <%= link_to 'Part ordering', show_production_path( part.id ), class: "btn btn-info" %>
  <br>
  <br>
<%end%>

<%=render( 'prod_types/show' )%>

<%= link_to 'Only in stock',   prod_type_path( @prod_type.id, only_in_stock: true ),   class: "btn btn-info" %>
<%= link_to 'Only available',  prod_type_path( @prod_type.id, only_available: true ),  class: "btn btn-info" %>
<%= link_to 'Only unassigned', prod_type_path( @prod_type.id, only_unassigned: true ), class: "btn btn-info" %>
<%= link_to 'All products',    prod_type_path( @prod_type.id, all_products: true ),    class: "btn btn-info" %>
<br>

<%=render( 'products/index' )%>
<br>

<%if part%>
  <%ordered_cnt, items = part.ordered_cnt%>
  <%if ordered_cnt && (ordered_cnt > 0) %>
    <h2>
      Part corresponding to this product type is in orderer. Order(s) are placed for <%=ordered_cnt.to_s%> pieces totally.
    </h2>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>
            Cnt
          </td>
          <td>
            Contract
          </td>
        </tr>
      </thead>
      <tbody>
        <%items.each do |item|%>
          <tr>
            <td>
              <%=lint_to( item.cnt, item_path( item.id ) )%>
            </td>
            <td>
              <%c = item.contract()%>
              <%if c%>
                link_to( c.name, contract_path( c.id ) )
              <%else%>
                <%=c.name%>
              <%end%>
            </td>

          </tr>
        <%end%>
      </tbody>
    </table>
    <br>
  <%end%>
<%end%>


<%contracts = @prod_type.contracts()%>
<%if contracts.size > 0%>
  <h2>List of pending contracts this product type is included in.</h2>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <td>
          Contract name
        </td>
        <td>
          Cnt
        </td>
      </tr>
    </thead>

    <tbody>
      <%contracts.each do |c, cnt|%>
        <tr>
          <td>
            <%=link_to( c.name, contract_path( c.id ) )%>
          </td>
          <td>
            <%=cnt.to_s%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <br>
<%end%>



<h2>Attachments list</h2>
<table class="table table-bordered table-hover">
  <%@prod_type.attachments.each do |att|%>
    <tr>
      <td>
        <%=link_to att.file_file_name, att.file.url%>
      </td>
      <td>
        <%= att.desc %>
      </td>
    </tr>
  <%end%>
</table>

<h2>Add another attachment</h2>
<%= form_tag( prod_type_add_attachment_path( @prod_type.id ), multipart: true ) do %>
  <%= file_field_tag :file %>
  <%= text_area_tag  :desc %>
  <%= submit_tag 'Append attachment and/or description', class: 'btn btn-warning' %>
<%end%>


<% if @prod_type.part_id %>
  <%= link_to 'Part', part_path( @prod_type.part_id ) %> | 
<% end %>
<%= link_to 'All product types', prod_types_path %> | 
<%= link_to 'Edit',              edit_prod_type_path(@prod_type) %>