config/routes.rb
Train01::Application.routes.draw do
  resources :shipments

  resources :prod_subtypes

  resources :logs

  resources :contract_items

  resources :contracts
  match     '/contracts/:id/add_item',                to: 'contracts#add_item',            via: :get,  as: :add_contract_item
  match     '/contracts/:id/assign_item/:item_id',    to: 'contracts#assign_item',         via: :get,  as: :assign_contract_item_product
  match     '/contracts/:id/unassign_item',           to: 'contracts#unassign_item',       via: :post, as: :unassign_contract_item
  match     '/contracts/:id/adjust',                  to: 'contracts#adjust',              via: :post, as: :adjust_contract
  match     '/date_parts_required',                   to: 'contracts#parts_required',      via: :get,  as: :date_parts_required
  match     '/contracts_update',                      to: 'contracts#contracts_update',    via: :post, as: :contracts_update
  match     '/contracts/:id/copy',                    to: 'contracts#copy',                via: :post, as: :copy_contract
  match     '/contracts/:id/packing_list',            to: 'contracts#packing_list',        via: :get,  as: :packing_list
  match     '/contracts/:id/user_packing_list',       to: 'contracts#user_packing_list',   via: :get,  as: :user_packing_list
  match     '/contracts/:id/followup_packing_list',   to: 'contracts#followup_packing_list',  via: :get,  as: :followup_packing_list
  match     '/contracts/:id/inventory_packing_list',  to: 'contracts#inventory_packing_list', via: :get,  as: :inventory_packing_list
  match     '/contracts/:id/ship_assigned_items',     to: 'contracts#ship_assigned_items', via: :post, as: :ship_assigned_items
  match     '/contracts/:id/add_attachment',          to: 'contracts#add_attachment',      via: :post, as: :contract_add_attachment
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number',       via: :get,  as: :change_number
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number_apply', via: :post, as: :change_number_apply
  match     '/contracts/:id/add_ship_date',           to: 'contracts#add_ship_date',       via: :post, as: :add_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date',       via: :get,  as: :set_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date_apply', via: :post, as: :set_ship_date_apply
  match     '/contracts/:id/change_box',              to: 'contracts#change_box',          via: :get,  as: :change_contract_box
  match     '/contracts/:id/change_box',              to: 'contracts#change_box_apply',    via: :post, as: :change_contract_box_apply

  resources :product_statuses

  resources :products
  match     '/products/:id/change_box',     to: 'products#change_box',          via: :get,  as: :change_product_box
  match     '/products/:id/change_box',     to: 'products#change_box_apply',    via: :post, as: :change_product_box_apply
  match     '/products/:id/add_attachment', to: 'products#add_attachment',      via: :post, as: :product_add_attachment
  
  resources :prod_types
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype',          via: :get,  as: :add_prod_subtype
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype_apply',    via: :post
  match     '/prod_types/:id/remove_subtype', to: 'prod_types#remove_subtype_apply', via: :post, as: :remove_prod_subtype
  match     '/prod_types/:id/adjust',         to: 'prod_types#adjust',               via: :post, as: :adjust_prod_type
  match     '/prod_types/:id/add_attachment', to: 'prod_types#add_attachment',       via: :post, as: :prod_type_add_attachment

  resources :image_to_parts

  resources :attachments

  resources :item_statuses

  resources :part_types

  resources :image_to_samples

  resources :samples
  match     'samples/:id',     to: 'samples#add_image', via: :post
  match     'samples/:id/change_box', to: 'samples#change_box',          via: :get,  as: :change_sample_box
  match     'samples/:id/change_box', to: 'samples#change_box_apply',    via: :post, as: :change_sample_box_apply

  resources :warehouses

  resources :part_insts
  match     '/part_insts/create',    to: 'part_insts#create',     via: :post, as: :create_part_inst

  resources :boxes
  match     '/boxes/:id/content',    to: 'boxes#content',         via: :get, as: :inspect_content
  match     '/boxes/:id/content',    to: 'boxes#merge_identical', via: :post, as: :merge_identical
  match     '/boxes/:id/add/:part',  to: 'boxes#add',             via: :get, as: :add_part_insts
  match     '/boxes/:id/add/:part',  to: 'boxes#add_apply',       via: :post
  match     '/boxes/:id/take/:part', to: 'boxes#take',            via: :get, as: :take_part_insts
  match     '/boxes/:id/take/:part', to: 'boxes#take_apply',      via: :post
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part',  via: :get, as: :add_new_part_to_box
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part_apply', via: :post

  resources :subparts

  resources :parts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts',          via: :get,  as: :add_subparts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts_apply',    via: :post
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts',       via: :get,  as: :remove_subparts
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts_apply', via: :post
  match      'parts/:id/estimate',         to: 'parts#estimate',              via: :get,  as: :estimate
  match      'parts/:id/estimate',         to: 'parts#estimate_take',         via: :post
  match      'parts/:id/show_production',  to: 'parts#show_production',       via: :get,  as: :show_production
  match      'parts/:id/show_production_apply', to: 'parts#show_production_apply', via: :post
  match      'parts/:id/add_image',        to: 'parts#add_image',             via: :post, as: :part_add_image
  match      'parts/:id/add_attachment',   to: 'parts#add_attachment',        via: :post, as: :part_add_attachment
  match      'parts/:id/copy',             to: 'parts#copy',                  via: :post, as: :copy_part
  match      'parts/:id/bom',              to: 'parts#bom',                   via: :get,  as: :part_bom
  
  resources :items
  match     '/items/:id/convert_form',     to: 'items#convert_form', via: :get,  as: :convert_form
  match     '/items/:id/convert_form',     to: 'items#convert',      via: :post
  match     '/my_items',                   to: 'items#my',           via: :get,  as: :my_items
  match     '/items/:id/copy',             to: 'items#copy',         via: :get,  as: :copy_item
  match     '/items/:id/copy',             to: 'items#copy_submit',  via: :post
  
  resources :orders

  
  get "static_pages/index"
  match '/static_pages/submit',            to: 'static_pages#submit',            via: :post
  match '/static_pages/submitImage',       to: 'static_pages#submitImage',       via: :post
  match '/static_pages/new_user_form',     to: 'static_pages#new_user_form',     via: :get
  match '/static_pages/user_sign_in_form', to: 'static_pages#user_sign_in_form', via: :get
  match '/static_pages/user_sign_in',      to: 'static_pages#user_sign_in',      via: :post
  match '/static_pages/user_sign_out',     to: 'static_pages#user_sign_out',     via: :post
  match '/static_pages/user_register',     to: 'static_pages#user_register',     via: :post, as: :user_register

  root 'static_pages#index'

  resources :users
  match "/users",            to: "users#all",     via: :get,        as: :users_all
  get   "/users/:id"         =>  "users#show",    as:  :users_show
  get   "/users/:id/edit"    =>  "users#edit",    as:  :users_edit
  match "/users/:id/update", to: "users#update",  via: :post

  resources :orders
  match     "/orders/update", to: "orders#update",  via: :post
  get       "/my_orders"      => "orders#my_orders", as: :my_orders

end

app/models/box.rb
# == Schema Information
#
# Table name: boxes
#
#  id           :integer          not null, primary key
#  box_id       :string(255)
#  desc         :text
#  created_at   :datetime
#  updated_at   :datetime
#  warehouse_id :integer
#

class Box < ActiveRecord::Base
  belongs_to :user
  belongs_to :warehouse
  has_many   :part_insts

  attr_accessible :box_id
  attr_accessible :desc
  attr_accessible :warehouse_id

  def products()
  	prods = Product.where( box_id: self.id )
  	return prods
  end

  def samples()
    samps = Sample.where( box_id: self.id )
    return samps
  end

  def warehouse()
  	wh = Warehouse.exists?( self.warehouse_id )
  	if ( not wh )
  		return nil
  	end
  	wh = Warehouse.find( self.warehouse_id )
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  include UsersHelper
  include PartsHelper
  include LogsHelper

  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @user = current_user
    if ( params[:search] && (params[:search].size > 0) )
      @boxes = search( Box, params[:search], [ "box_id", "desc" ] )
      @paginate = false
    else
      @boxes = Box.paginate( page: params[ :page ], per_page: 30 )
      @paginate = true
    end

    @warehouses = Warehouse.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @user = current_user
    @box  = Box.find( params[ :id ] )
    @wh   = @box.warehouse

    @part_insts = PartInst.where( box_id: params[ :id ] )
    @parts = []
    @part_insts.each do |pi|
      part = Part.find( pi.part_id )
      @parts.append( {part: part, inst: pi} )
    end
  end

  # GET /boxes/new
  def new
    @user = current_user
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
    @user = current_user
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @user = current_user
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        log( "New box " + box_params[ :box_id ] + " is created", @user )

        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render action: 'show', status: :created, location: @box }
      else
        format.html { render action: 'new' }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @box.update(box_params)
        log( "Box " + box_params[ :box_id ] + " is changed", @user )
        
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @user = current_user
    log( "Box " + @box.box_id + " is destroyed", @user )
    @box.destroy
        
    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end

  # content /boxes/1/content
  def content
      @user = current_user
      @box = Box::find( params[ :id ] )
      @part_insts = PartInst.where( box_id: params[ :id ] )
      @parts = []
      @part_insts.each do |pi|
        part = Part.find( pi.part_id )
        @parts.append( {part: part, inst: pi} )
      end
  end

  # This is an action.
  def merge_identical
      @user = current_user
      @box = Box::find( params[ :id ] )
      while true do
          @part_insts = @box.part_insts
          insts = []
          @part_insts.each do |pi|
            insts.append( {id: pi.id, cnt: pi.cnt, part_id: pi.part_id} )
          end
          iters = 0
          insts.each do |a|
              insts.each do |b|
                  if ((a != b) && ( a[:part_id] == b[:part_id] )) then
                      pi_a = PartInst.find( a[:id] )
                      pi_b = PartInst.find( b[:id] )
                      pi_a.cnt = a[:cnt] + b[:cnt]
                      pi_a.save
                      pi_b.delete
                      iters += 1
                      break
                  end
              end
              if ( iters > 0 ) then
                  break
              end
          end
          if ( iters == 0 ) then
              break
          end
      end
      redirect_to box_path( @box.id ), notice: 'Merge successfull.'
  end

  # /boxes/:id/add/:part
  def add
      @add = true
      @add_or_take = "Adding"
      @user = current_user
      @box = Box.find( params[ :id ] )
      @part_inst = PartInst.find( params[ :part ] )
      @part      = Part.find( @part_inst.part_id )
  end

  def add_apply
      cnt = params[ :cnt ].to_i
      @user = current_user
      @box = Box::find( params[ :id ] )
      @part_inst = PartInst.find( params[ :part ] )
      old_cnt = @part_inst.cnt
      @part_inst.cnt = @part_inst.cnt + cnt
      if ( @part_inst.save ) then
          log( "Parts cnt is changed from " + old_cnt.to_s + " to " + @part_inst.cnt.to_s + " in box " + @box.box_id, @user )
          redirect_to inspect_content_path( @box.id ), notice: "#{cnt} parts\'ve been added sucessfully!"
      else
          render take_part_insts_path, notice: "Failed to add #{cnt} items to this box!"
      end
  end

  # /boxes/:id/take/:part
  def take
      @add = false
      @add_or_take = "Taking"
      @user = current_user
      @box = Box.find( params[ :id ] )
      @part_inst = PartInst.find( params[ :part ] )
      @part      = Part.find( @part_inst.part_id )
      #@cnt_max   = @part_inst.cnt
      #@cnt_min   = ( @cnt_max > 0 ) ? 1 : 0
  end

  def take_apply
      cnt = params[ :cnt ].to_i
      @user = current_user
      @box = Box::find( params[ :id ] )
      @part_inst = PartInst.find( params[ :part ] )
      if ( cnt > @part_inst.cnt ) then
          render take_part_insts_path, notice: "Failed to get #{cnt} pieces, too few items (#{@part_inst.cnt}) available!"
          return
      end
      old_cnt = @part_inst.cnt
      @part_inst.cnt = @part_inst.cnt - cnt
      if ( @part_inst.save ) then
          log( "Parts cnt is changed from " + old_cnt.to_s + " to " + @part_inst.cnt.to_s + " in box " + @box.box_id, @user )

          redirect_to inspect_content_path( @box.id ), notice: "#{cnt} parts\'ve been taken sucessfully!"
      else
          render take_part_insts_path, notice: "Failed to get #{cnt} items form this box!"
      end
  end

  def add_new_part
    @user = current_user
    @box  = Box.find( params[ :id ] )
    if params[ :search ] then
      @parts    = search( Part, params[ :search ], ['own_id', 'third_id', 'desc'] )
      @paginate = false
    else
      @parts    = Part.paginate( page: params[ :page ], per_page: 10 )
      @paginate = true
    end
  end

  def add_new_part_apply
    part_inst = PartInst.new
    part_inst.box_id = params[ :id ]
    part_inst.part_id = params[ :part_id ]
    part_inst.cnt = params[ :cnt ]
    if ( part_inst.save ) then
      redirect_to box_path( params[:id], notice: "Added new part(s) to this box" )
    else
      redirect_to add_new_part_to_box_path( params[ :id ] ), notice: "Failed to add part(s) to this box"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
        if params[:box] then
            params.require( :box ).permit( :box_id, :desc, :warehouse_id )
        end
    end

    def wh_list
        #@wh = options_from_collection_for_select( Warehouse.all, :id, :w_id )
        #return @wh
        return nil
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_add_take.html.erb
<h1><%= @add_or_take %> the following part(s) to/from the box <b><%= @box.box_id %></b></h1>
<p id="notice"><%= notice %></p>

<% func = ( @add ) ? add_part_insts_path : take_part_insts_path%>
<%= form_tag( func ) do%>
    <%= render 'part_insts/show' %>
	<div class="form-group">
	    <%= label_tag :cnt %><br>
	    <%= number_field_tag :cnt, 1, class: "form-control" %>
	</div>
	<div class="actions">
	    <%= submit_tag "Submit", class: "btn btn-danger" %>
	</div>
<% end %>

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Warehouse id" %><br>
    <%= f.select( :warehouse_id, options_from_collection_for_select( Warehouse.all, :id, :w_id ) ) %>
  </div>
  <div class="form-group">
    <%= f.label "Short box id" %><br>
    <%= f.text_field :box_id %>
  </div>
  <div class="form-group">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/_show.html.erb
<p>
    <strong>"Warehouse id"</strong>
    <%if @box.warehouse then%>
        <%= @box.warehouse.w_id %>
    <%else%>
        Unavailable
    <%end%>
</p>
<p>
    <strong>"Warehouse image"</strong>
    <%if @box.warehouse then%>
        <a href="<%=@box.warehouse.image.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
            <%=image_tag( @box.warehouse.image.url(:thumb) )%>
        </a>
    <%else%>
      Unspecified
  <%end%>
</p>
<p>
  <strong>Box:</strong>
  <%= @box.box_id %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @box.desc %>
</p>

app/views/boxes/add.html.erb
<%= render 'add_take' %>

app/views/boxes/add_new_part.html.erb
<h1>
  Add part(s) to box "<%= @box.box_id %>"
</h1>

<h2>
  <%= @box.desc %>
</h2>

<%= form_tag( add_new_part_to_box_path ) do |f| %>
  <% if @part_inst && @part_inst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part_inst.errors.count, "error") %> prohibited this part_inst from being saved:</h2>

      <ul>
      <% @part_inst.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag :cnt %><br>
    <%= number_field_tag :cnt, 1 %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Parts</th>
        <th>Boxes</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>
            <%if @paginate then%>
                <%=will_paginate @parts, renderer: BootstrapPagination::Rails %>
            <%end%>
            <ul>
                <% @parts.each do |part| %>
                  <li>
                      <%= radio_button_tag :part_id, part.id, "#{part.own_id}" %>
                      <% @part = part %>
                      <%= render 'parts/show' %>
                  </li>
                <%end%>
            </ul>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= submit_tag "Add new part" %>
  </div>


<% end %>

app/views/boxes/content.html.erb
<h1>Box <b><%= @box.box_id %></b> content</h1>

<%= link_to 'Add new part(s)', add_new_part_to_box_path( @box.id )%>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Own id</th>
      <th>Third id</th>
      <th>Cnt</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |a| %>
      <tr>
        <td>
            <a href="<%=a[:part].image.url( :original ).sub( /\?\d+/i, "" )%>" rel="facebox" >
                <%=image_tag( a[:part].image.url( :thumb ) )%>
            </a>
        </td>
        <td><%= a[:part].own_id %></td>
        <td><%= a[:part].third_id %></td>
        <td><%= a[:inst].cnt %></td>
        <td><%= link_to 'Show part', part_path( a[:part].id ), class: "btn btn-success" %>
        <td><%= link_to 'Add items', add_part_insts_path( @box.id, a[:inst].id ), class: "btn btn-success" %></td>
        <td><%= link_to 'Take items', take_part_insts_path( @box.id, a[:inst].id ), class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_for(@box, :html => { :multipart => true }) do |f| %>
  <div class="actions">
    <%= f.submit "Merge identical parts in this box", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<%=link_to( "All warehousies list", warehouses_path, class: 'btn btn-info' )%>
<br>
<br>

<%= link_to 'Add new box', new_box_path, class: "btn btn-warning" %>
<br>

<%if @paginate%>
  <%=will_paginate( @boxes, renderer: BootstrapPagination::Rails )%>
<%end%>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Warehouse</th>
      <th>Box</th>
      <th>Desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td>
            <%if box.warehouse then %>
                <%=box.warehouse.w_id%>
            <%else%>
                Unspecified
            <%end%>
        </td>
        <td><%= box.box_id %></td>
        <td><%= box.desc %></td>
        <td><%= link_to 'Show', box, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_box_path(box), class: 'btn btn-warning' %></td>
        <% if false then %>
            <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new box', new_box_path, class: "btn btn-warning" %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Add new part(s)', add_new_part_to_box_path( @box.id )%>

<%= render 'boxes/show' %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Own id</th>
      <th>Third id</th>
      <th>Cnt</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |a| %>
      <tr>
        <td>
            <a href="<%=a[:part].image.url( :original ).sub( /\?\d+/i, "" )%>" rel="facebox" >
                <%=image_tag( a[:part].image.url( :thumb ) )%>
            </a>
        </td>
        <td><%= a[:part].own_id %></td>
        <td><%= a[:part].third_id %></td>
        <td><%= a[:inst].cnt %></td>
        <td><%= link_to 'Show part', part_path( a[:part].id ), class: "btn btn-success" %>
        <td><%= link_to 'Add items', add_part_insts_path( @box.id, a[:inst].id ), class: "btn btn-success" %></td>
        <td><%= link_to 'Take items', take_part_insts_path( @box.id, a[:inst].id ), class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_tag( merge_identical_path( @box.id ), :method => 'post' ) do %>
  <div class="actions">
    <%= submit_tag "Merge identical parts in this box", class: "btn btn-danger" %>
  </div>
<% end %>
<br>
<br>

<%@products = @box.products%>
<%if @products.size > 0%>
  <h2>Products list</h2>
  <%=render( 'products/index' )%>
  <br>
<%end%>

<%@samples = @box.samples%>
<%if @samples.size > 0%>
  <h2>Samples list</h2>
  <table class="table table-bordered table-hover">
    <%@samples.each do |sample|%>
      <tr>
        <td>
          <%=link_to( sample.from, sample_path( sample.id ) )%>
        </td>
        <td>
          <%=sample.desc%>
        </td>
      </tr>
    <%end%>
  </table>
  <br>
<%end%>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>
<%= link_to 'Add items', add_new_part_to_box_path( @box.id ) %>
<% if false then %>
  <%= link_to 'Inspect content', inspect_content_path( @box.id ) %>
<% end %>

app/views/boxes/take.html.erb
<%= render 'add_take' %>