config/routes.rb
Train01::Application.routes.draw do
  resources :shipments

  resources :prod_subtypes

  resources :logs

  resources :contract_items

  resources :contracts
  match     '/contracts/:id/add_item',                to: 'contracts#add_item',            via: :get,  as: :add_contract_item
  match     '/contracts/:id/assign_item/:item_id',    to: 'contracts#assign_item',         via: :get,  as: :assign_contract_item_product
  match     '/contracts/:id/unassign_item',           to: 'contracts#unassign_item',       via: :post, as: :unassign_contract_item
  match     '/contracts/:id/adjust',                  to: 'contracts#adjust',              via: :post, as: :adjust_contract
  match     '/date_parts_required',                   to: 'contracts#parts_required',      via: :get,  as: :date_parts_required
  match     '/contracts_update',                      to: 'contracts#contracts_update',    via: :post, as: :contracts_update
  match     '/contracts/:id/copy',                    to: 'contracts#copy',                via: :post, as: :copy_contract
  match     '/contracts/:id/packing_list',            to: 'contracts#packing_list',        via: :get,  as: :packing_list
  match     '/contracts/:id/user_packing_list',       to: 'contracts#user_packing_list',   via: :get,  as: :user_packing_list
  match     '/contracts/:id/followup_packing_list',   to: 'contracts#followup_packing_list',  via: :get,  as: :followup_packing_list
  match     '/contracts/:id/inventory_packing_list',  to: 'contracts#inventory_packing_list', via: :get,  as: :inventory_packing_list
  match     '/contracts/:id/ship_assigned_items',     to: 'contracts#ship_assigned_items', via: :post, as: :ship_assigned_items
  match     '/contracts/:id/add_attachment',          to: 'contracts#add_attachment',      via: :post, as: :contract_add_attachment
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number',       via: :get,  as: :change_number
  match     '/contracts/:id/change_number/:item',     to: 'contracts#change_number_apply', via: :post, as: :change_number_apply
  match     '/contracts/:id/add_ship_date',           to: 'contracts#add_ship_date',       via: :post, as: :add_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date',       via: :get,  as: :set_ship_date
  match     '/contracts/:id/set_ship_date/:item',     to: 'contracts#set_ship_date_apply', via: :post, as: :set_ship_date_apply
  match     '/contracts/:id/change_box',              to: 'contracts#change_box',          via: :get,  as: :change_contract_box
  match     '/contracts/:id/change_box',              to: 'contracts#change_box_apply',    via: :post, as: :change_contract_box_apply

  resources :product_statuses

  resources :products
  match     '/products/:id/change_box',     to: 'products#change_box',          via: :get,  as: :change_product_box
  match     '/products/:id/change_box',     to: 'products#change_box_apply',    via: :post, as: :change_product_box_apply
  match     '/products/:id/add_attachment', to: 'products#add_attachment',      via: :post, as: :product_add_attachment
  
  resources :prod_types
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype',          via: :get,  as: :add_prod_subtype
  match     '/prod_types/:id/add_subtype',    to: 'prod_types#add_subtype_apply',    via: :post
  match     '/prod_types/:id/remove_subtype', to: 'prod_types#remove_subtype_apply', via: :post, as: :remove_prod_subtype
  match     '/prod_types/:id/adjust',         to: 'prod_types#adjust',               via: :post, as: :adjust_prod_type
  match     '/prod_types/:id/add_attachment', to: 'prod_types#add_attachment',       via: :post, as: :prod_type_add_attachment

  resources :image_to_parts

  resources :attachments

  resources :item_statuses

  resources :part_types

  resources :image_to_samples

  resources :samples
  match     'samples/:id',     to: 'samples#add_image', via: :post
  match     'samples/:id/change_box', to: 'samples#change_box',          via: :get,  as: :change_sample_box
  match     'samples/:id/change_box', to: 'samples#change_box_apply',    via: :post, as: :change_sample_box_apply

  resources :warehouses

  resources :part_insts
  match     '/part_insts/create',    to: 'part_insts#create',     via: :post, as: :create_part_inst

  resources :boxes
  match     '/boxes/:id/content',    to: 'boxes#content',         via: :get, as: :inspect_content
  match     '/boxes/:id/content',    to: 'boxes#merge_identical', via: :post, as: :merge_identical
  match     '/boxes/:id/add/:part',  to: 'boxes#add',             via: :get, as: :add_part_insts
  match     '/boxes/:id/add/:part',  to: 'boxes#add_apply',       via: :post
  match     '/boxes/:id/take/:part', to: 'boxes#take',            via: :get, as: :take_part_insts
  match     '/boxes/:id/take/:part', to: 'boxes#take_apply',      via: :post
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part',  via: :get, as: :add_new_part_to_box
  match     '/boxes/:id/add_new_part', to: 'boxes#add_new_part_apply', via: :post

  resources :subparts

  resources :parts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts',          via: :get,  as: :add_subparts
  match      'parts/:id/add_subparts',     to: 'parts#add_subparts_apply',    via: :post
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts',       via: :get,  as: :remove_subparts
  match      'parts/:id/remove_subparts',  to: 'parts#remove_subparts_apply', via: :post
  match      'parts/:id/estimate',         to: 'parts#estimate',              via: :get,  as: :estimate
  match      'parts/:id/estimate',         to: 'parts#estimate_take',         via: :post
  match      'parts/:id/show_production',  to: 'parts#show_production',       via: :get,  as: :show_production
  match      'parts/:id/show_production_apply', to: 'parts#show_production_apply', via: :post
  match      'parts/:id/add_image',        to: 'parts#add_image',             via: :post, as: :part_add_image
  match      'parts/:id/add_attachment',   to: 'parts#add_attachment',        via: :post, as: :part_add_attachment
  match      'parts/:id/copy',             to: 'parts#copy',                  via: :post, as: :copy_part
  match      'parts/:id/bom',              to: 'parts#bom',                   via: :get,  as: :part_bom
  
  resources :items
  match     '/items/:id/convert_form',     to: 'items#convert_form', via: :get,  as: :convert_form
  match     '/items/:id/convert_form',     to: 'items#convert',      via: :post
  match     '/my_items',                   to: 'items#my',           via: :get,  as: :my_items
  match     '/items/:id/copy',             to: 'items#copy',         via: :get,  as: :copy_item
  match     '/items/:id/copy',             to: 'items#copy_submit',  via: :post
  
  resources :orders

  
  get "static_pages/index"
  match '/static_pages/submit',            to: 'static_pages#submit',            via: :post
  match '/static_pages/submitImage',       to: 'static_pages#submitImage',       via: :post
  match '/static_pages/new_user_form',     to: 'static_pages#new_user_form',     via: :get
  match '/static_pages/user_sign_in_form', to: 'static_pages#user_sign_in_form', via: :get
  match '/static_pages/user_sign_in',      to: 'static_pages#user_sign_in',      via: :post
  match '/static_pages/user_sign_out',     to: 'static_pages#user_sign_out',     via: :post
  match '/static_pages/user_register',     to: 'static_pages#user_register',     via: :post, as: :user_register

  root 'static_pages#index'

  resources :users
  match "/users",            to: "users#all",     via: :get,        as: :users_all
  get   "/users/:id"         =>  "users#show",    as:  :users_show
  get   "/users/:id/edit"    =>  "users#edit",    as:  :users_edit
  match "/users/:id/update", to: "users#update",  via: :post

  resources :orders
  match     "/orders/update", to: "orders#update",  via: :post
  get       "/my_orders"      => "orders#my_orders", as: :my_orders

end

app/models/part_inst.rb
# == Schema Information
#
# Table name: part_insts
#
#  id         :integer          not null, primary key
#  part_id    :integer
#  box_id     :integer
#  cnt        :integer
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class PartInst < ActiveRecord::Base
  belongs_to :part
  belongs_to :box
  belongs_to :user

  attr_accessible :part_id
  attr_accessible :box_id
  attr_accessible :cnt

end

app/controllers/part_insts_controller.rb
class PartInstsController < ApplicationController
  before_action :set_part_inst, only: [:show, :edit, :update, :destroy]

  include UsersHelper
  include PartsHelper
  include LogsHelper

  # GET /part_insts
  # GET /part_insts.json
  def index
    @user = current_user
    if params[ :search ] && (params[ :search ].length > 0) then
        @parts = search( Part, params[ :search ], ['own_id', 'third_id', 'desc'] )
        @part_insts = nil
        @parts.each do |part|
            pis = PartInst.where( part_id: part.id )
            if ( @part_insts ) then
                @part_insts = @part_insts + pis
            else
                @part_insts = pis
            end
        end
        @paginate = false
    else
        @part_insts = PartInst.paginate( page: params[ :page ], per_page: 10 )
        @paginate = true
    end
    @boxes      = Box.all
  end

  # GET /part_insts/1
  # GET /part_insts/1.json
  def show
    @user = current_user
  end

  # GET /part_insts/new
  def new
    @user  = current_user
    if ( params[ :search ] && (params[ :search ].length > 0) ) then
        @parts = search( Part, params[:search], [ 'own_id', 'third_id', 'desc' ] )
        @paginate_parts = false
    else
        @parts = Part.paginate( page: params[ :part_page ], per_page: 10 )
        @paginate_parts = true
    end
    @boxes = Box.paginate( page: params[ :box_page ], per_page: 10 )
    @paginate_boxes = true
    #@part_inst = PartInst.new
  end

  # GET /part_insts/1/edit
  def edit
    @user      = current_user
    @part_inst = PartInst.find( params[ :id ] )
  end

  # POST /part_insts
  # POST /part_insts.json
  def create
    @user = current_user
    @part_inst        = PartInst.new
    @part_inst.cnt    = params[ :cnt ]
    @part_inst.box_id  = params[ :box_id ]
    @part_inst.part_id = params[ :part_id ]

    if @part_inst.save
      log( "New part instance is created", @user )
      
      redirect_to @part_inst, notice: 'Part inst was successfully created.'
    else
        render action: 'new'
    end
  end

  # PATCH/PUT /part_insts/1
  # PATCH/PUT /part_insts/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @part_inst.update(part_inst_params)
        log( "Part instance is adjusted", @user )
        
        format.html { redirect_to @part_inst, notice: 'Part inst was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @part_inst.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /part_insts/1
  # DELETE /part_insts/1.json
  def destroy
    @user = current_user
    @part_inst.destroy
    respond_to do |format|
      format.html { redirect_to part_insts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part_inst
      @part_inst = PartInst.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_inst_params
      if ( params && params[ :part_inst ] ) then
          params.require(:part_inst).permit(:part_id, :box_id, :cnt)
      end
    end
end

app/helpers/part_insts_helper.rb
module PartInstsHelper
end

app/views/part_insts/_form.html.erb
<%= form_for(@part_inst) do |f| %>
  <% if @part_inst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part_inst.errors.count, "error") %> prohibited this part_inst from being saved:</h2>

      <ul>
      <% @part_inst.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :part_id %><br>
    <%= f.number_field :part_id, class: "from-control" %>
  </div>
  <div class="form-group">
    <%= f.label :box_id %><br>
    <%= f.number_field :box_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cnt %><br>
    <%= f.number_field :cnt, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/part_insts/_new_form.html.erb
<%= form_tag( create_part_inst_path ) do |f| %>
  <% if @part_inst && @part_inst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part_inst.errors.count, "error") %> prohibited this part_inst from being saved:</h2>

      <ul>
      <% @part_inst.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag :cnt %><br>
    <%= number_field_tag :cnt, value: 1, class="form-control" %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Parts</th>
        <th>Boxes</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>
            <%if @paginate_parts then%>
              <%=will_paginate @parts, param_name: :part_page, renderer: BootstrapPagination::Rails %>
            <%end%>
            <ul>
                <% @parts.each do |part| %>
                  <li>
                    <%= radio_button_tag :part_id, part.id, "#{part.own_id}" %>
                    <% @part = part %>
                    <%= render 'parts/show' %>
                  </li>
                <%end%>
            </ul>
        </td>
        <td>
            <%if @paginate_boxes then%>
              <%= will_paginate @boxes, param_name: :box_page, renderer: BootstrapPagination::Rails %>
            <%end%>
            <ul>
              <% @boxes.each do |box| %>
                <li>
                    <%= radio_button_tag :box_id, box.id, "box" %>
                    <% @box = box %>
                    <%= render 'boxes/show'%>
                </li>
              <% end %>
            </ul>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= submit_tag "Create" %>
  </div>


<% end %>

app/views/part_insts/_show.html.erb
<p>
  <strong>Cnt: <%= @part_inst.cnt %></strong>
</p>

<p>
  <strong>Part: "<%= @part.own_id %>", "<%= @part.third_id %>"</strong>
</p>

<p>
    <a href="<%=@part.image.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
        <%=image_tag( @part.image.url(:thumb) )%>
    </a>
</p>

<p>
  <strong>Box:</strong>
  <%= @part_inst.box_id %>
</p>

app/views/part_insts/edit.html.erb
<h1>Editing part_inst</h1>

<%= render 'form' %>

<%= link_to 'Show', @part_inst %> |
<%= link_to 'Back', part_insts_path %>

app/views/part_insts/index.html.erb
<h1>Listing part_insts</h1>

<% if @paginate || (@paginate == nil) then %>
  <%= will_paginate @part_insts, renderer: BootstrapPagination::Rails %>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Image</th>
      <th>Part</th>
      <th>Box</th>
      <th>Cnt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @part_insts.each do |part_inst| %>
      <tr>
        <%if Part.exists?( part_inst.part_id ) then%>
            <%part = Part.find( part_inst.part_id )%>
        <%end%>
        <%if Box.exists?( part_inst.box_id ) then%>
            <%box  = @boxes.find( part_inst.box_id )%>
        <%end%>
        <%if part then%>
            <td>
                <a href="<%=part.image.url(:original).sub( /\?\d+/i, "" )%>" rel="facebox" >
                    <%=image_tag( part.image.url(:thumb) )%>
                </a>
            </td>
            <td>
                <%= part.own_id %>
            </td>
            <td>
              <%if box then%>
                  <%= link_to( box.box_id, inspect_content_path( box.id ) ) %>
              <%else%>
                  Unspecified
              <%end%>
            </td>
            <td><%= part_inst.cnt %></td>
            <td><%= link_to 'Show', part_path(part), class: 'btn btn-success' %></td>
            <% if false then %>
                <td><%= link_to 'Edit', edit_part_inst_path(part_inst) %></td>
                <td><%= link_to 'Destroy', part_inst, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part inst', new_part_inst_path, class: 'btn btn-warning' %>

app/views/part_insts/new.html.erb
<h1>Create new part instance(s) using existing part types and warehouse boxes. If there is no such part type it should be <%=link_to "created", new_part_path%> first.</h1>


<%= render 'new_form' %>

<%= link_to 'Back', part_insts_path %>

app/views/part_insts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part:</strong>
  <%= @part_inst.part_id %>
</p>

<p>
  <strong>Box:</strong>
  <%= @part_inst.box_id %>
</p>

<p>
  <strong>Cnt:</strong>
  <%= @part_inst.cnt %>
</p>

<%= link_to 'Edit', edit_part_inst_path(@part_inst) %> |
<%= link_to 'Back', part_insts_path %>